#include "backstory.h"
#include <cstdlib>

std::string BIRTH(){
	std::string birth[] = {"You were born inside a river. Your parents thought it would be more natural.",
"You were born on a battlefield, slaughtering cows by the age of three.",
"You were born in a field. You are allergic to pollen and peanuts.",
"You were born next to a giant cockroach, giving you great strength.",
"You were born an orphaned ethnic baby into a world of poverty and despair.",
"You were born with a third arm. You eventually had it amputated.",
"You were born with a bag over your head. You were a very ugly baby.",
"You were born in a cave and echolocate via chewing with your mouth open.",
"You were born extremely overweight, weighing in at fifty pounds.",
"You were born a little bit early. You are very impatient.",
"You were born inside a barrel of pickles. You ate most of them.",
"You were born as a serf, but not the kowabunga kind.",
"You were born a genius, managing to put the round pegs in the square holes.",
"You were born next to an oak tree. You named it Gary Oak.",
"You were born near a mermaid. You find sushi inexplicably arousing.",
"You were born an accident. Your mother ate a live moose.",
"You were born to a pair of thespians. No, THESPIANS.",
"You were born under the stars and have an inexplicable fear of dippers.",
"You were born without a gall bladder. You use the restroom more than most.",
"You were born blind. A wizard granted you the eyes of an eagle named Ted.",
"You were born with your organs reversed and wished you were more special.",
"You were born to a blacksmith, your dad always got abused by heroes.",
"You were born rather oval. Your siblings used you as a football.",
"You were a stillbirth, but brought back with magic. Your life is a lie.",
"You were born completely alone with the power to make awkward friendships.",
"You consumed your baby twin. You currently have the strength of two babies.",
"You are left handed. You always felt 90%%%% more special than everyone else.",
"You were born to a wonderful family of storks. They fed you worms.",
"You think, therefore you are. You were always the most serious baby.",
"You were born a very old monk. You named yourself The Great One.",
"You were born very confused. You often wonder if you are human or a dancer.",
"You were born an old soul, always searching for the fountain of youth.",
"You were born in a manger. People herald your birth and hope for greatness.",
"You were born asexual, but with practice and elbow grease, you do just fine.",
"You were born mysteriously. People always asked you how is babby formed.",
"You were born with tongue as large as a walrus.",
"You were born a newt. You got better.",
"You were born into a family of cobblers. You have no sole.",
"You were birthed in a cannon and became the first baby to orbit the planet.",
"You can see why kids love the taste of Potion Berry Crunch.",
"You know how many licks it takes to get to the center of a Skunk Pop.",
"You were born so dumb, you're actually a genius.",
"You were born in the warm body cavity of an intelligent octopus.",
"You came out of the womb with a map, compass, and baggie of trailmix.",
"You were born so poor your family used your diapers as fireplace fuel.",
"You were a bug in your past life, which explains the extra toes.",
"You were born the heir to an Ancient Evil but lost it in a bet to a cow.",
"You turned the holy water at your baptism into tapioca pudding.",
"You were born a giant among mice. You're actually shorter than most humans."};
	return birth[std::rand() % 50];
}

std::string UPBRINGING(){
	std::string upbringing[] = {"Raised by two mentally challenged octopi, your childhood was ruined.",
"Raised by a pack of sloths, you never went anywhere in life.",
"Raised by an Amazonian mother, you were always into bigger women.",
"Raised by two elderly assassin nuns, your childhood was mostly badass.",
"Raised by nobles, you enjoy cream puffs and suffer from gout.",
"Raised by a pack of wolves, you can't resist sniffing people's butts.",
"Raised by salmon, you suffered from asthma until you got out of the water.",
"Raised by a pack of squirrels, you can't help but love nuts.",
"Raised by a shark, you are a horribly misunderstood killing machine.",
"Raised by a very tall man, you spent your days in his shadow.",
"Raised by dead ancestors, you hang around graveyards shouting at tombs.",
"Raised by an indecisive grandfather, your previous name was Bobert.",
"Raised by garden gnomes, you excel at staring at people from dark doorways.",
"Raised by a huge talking walrus, koo koo kachoo see how they run.",
"Raised by an anteater, you became a god among women in bed.",
"Raised by a sphinx, you only speak in riddles.",
"Raised by a bard, you only speak in metered rhyme.",
"Raised by hipster nudists, you wear clothes ironically.",
"Raised by busy parents, you had mostly imaginary friends.",
"Raised by demigods, you constantly feel under pressure to lift boulders.",
"Raised by a skunk, you had no childhood friends.",
"Raised by moles, you have a fondness for voles and digging holes.",
"Raised by seals, you have an overwhelming fear of clubs.",
"Raised in a circus, you can fit many people into very small spaces.",
"Raised by normal, middle-class parents, you are half human, half drone.",
"Raised by detectives, you constantly stumble onto rain-slicked streets.",
"Raised by moral thinkers, you find it hard to answer rhetorical questions.",
"Raised by two grandmothers, you have a secret attraction to old ladies.",
"Raised by a court jester, your favorite song is Jingle Bells.",
"Raised by a baker, you have some killer forearms from kneading.",
"Raised by a demanding mother, your biggest fear is to fail expectations.",
"Raised by a lackadaisical father, you find quests rather troublesome.",
"Raised by a lumberjack, you can grow a Manly Beard of Manliness.",
"Raised by a potato, you were always the brightest in the family.",
"Raised by a talking sword, you have a sharp tongue.",
"Raised by a pufferfish, your barbs would be poisonous, if you had any.",
"Raised by a club, you have an unhealthy obsession with seals.",
"Raised by a hedgehog, you love gold rings way too much.",
"Raised by a plumber, you have a surprisingly good jump.",
"Raised by a librarian, you are addicted to book glue.",
"Raised by a dragon, you have a strange attraction to dragonflies.",
"Raised by a pack of zombies, you BRRAAAIIIIINSSSSS.",
"Raised by a fairy godmother, your only wish was to not have glass clothes.",
"Raised by a band of merry men, you love wearing tights.",
"Raised by a rabi, you lived in constant fear of scissors.",
"Raised by a giant, magic beans give you gas. You bake terrible bread.",
"Raised by the mob, you excel at making Cement Shoes of Sinking +1.",
"Raised by bears, you're smarter than average and dress sharp.",
"Raised by orphans, you lived a hard knock life.",
"Raised by aliens, you have intimate knowledge of your own prostate."};
	return upbringing[std::rand() % 50];
}

std::string REGRET(){
	std::string regret[] = {"Getting kicked out of nude painting class has been your biggest regret.",
"Declining an invitation to Wizard U has been your biggest regret.",
"Drinking a gallon of melted cottage cheese has been your biggest regret.",
"Being so fat you really sit around the house has been your biggest regret.",
"Hooking up with a two-headed lizard man has been your biggest regret.",
"Making out with a giant broccoli has been your teeth's biggest regret.",
"Being impaled by a frozen fudge-covered banana has been your biggest regret.",
"Drinking a gallon of prune juice before a concert was your biggest regret.",
"Contemplating romance with a female cow has been your biggest regret.",
"Jumping into a pond of carnivorous tadpoles has been your biggest regret.",
"Using porcupine fur as toilet paper has been your biggest regret.",
"Using gasoline as an aftershave has been your biggest regret.",
"Using an old bear carcass as underwear has been your biggest regret.",
"Using beeswax for a laxative has always been your biggest regret.",
"Carving a potato sculpture of your naked self has been your biggest regret.",
"Trying to invent reusable marshmallows has been your biggest regret.",
"Drinking a potion that read DRINK ME has been your tiniest regret.",
"Trying to design an inflatable outhouse has been your biggest regret.",
"Trying to lick a platypus on a dare has been your biggest regret.",
"Recalling a past life as a sexual beagle has been your biggest regret.",
"Administering mouth-to-mouth to a crocodile has been your biggest regret.",
"Eating a moldy watermelon has always been your biggest regret.",
"Playing darts while blindfolded and naked has been your biggest regret.",
"Trying to use that vine as a swing has always been your biggest regret.",
"Injecting yourself with that random syringe has been your biggest regret.",
"Crossing your eyes and getting them stuck has been your biggest regret.",
"Spending time with a talking pig has always been your biggest regret.",
"An early gender changing surgery has always been your biggest regret.",
"Not being all you can be has always been your biggest regret.",
"Not being a nun has always been your biggest regret.",
"Rainy days and purple dinosaurs have always been your biggest regret.",
"Not planning for your retirement early has always been your biggest regret.",
"Eating that rotten apple you found has always been your biggest regret.",
"Forgetting to stretch before battle has always been your biggest regret.",
"Smacking kids with frozen celery has been your biggest regret.",
"You always regretted never going to clown school.",
"You wish you had known that knowing was half the battle.",
"Not assimilating into the collective has always been your biggest regret.",
"You regret breaking up with your girlfriend who was also a dead frog.",
"You regret taking your anger out on your cheese wheel that one night.",
"Your most recent regret is losing The Game.",
"You've always regretted kissing that singing fish.",
"Eating a yellow snow cone has always been your biggest regret.",
"Drinking someone else's milkshake has been your biggest regret.",
"Laughing at starving orphans has always been your biggest regret.",
"Thinking about your own conception night has been your biggest regret.",
"Learning what a prairie oyster is has been your biggest regret.",
"Accidentally blowing up a whale has been your biggest regret.",
"Peeing on a blind man from the rooftops has been your biggest regret.",
"You always regretted being a Bokononian. So it goes."};
	return regret[std::rand() % 50];
}

std::string ENJOY(){
	std::string enjoy[] = {"One to enjoy the more abstract concepts, you enjoy eating donuts.",
"One to enjoy weaponsmithing, you are far too fascinated with stones.",
"One to enjoy protesting, you have all kinds of picket signs.",
"One to enjoy lemon creme pie, you always cremed the competition.",
"One to enjoy alchemy, you're constantly freaking out, man.",
"One to enjoy gardening, you are very well grounded.",
"One to enjoy advanced physics, you definitely know the radius of a circle.",
"One to enjoy experimentation, you spend many hours mixing random chemicals.",
"One to enjoy extreme knitting, you like to create armor out of yarn.",
"One to enjoy watersports, you always liked extreme breaststroking.",
"One to have poor bowel control, you are always leaking everywhere.",
"One to enjoy firewalking, your feet are blackened with blisters.",
"One to enjoy fine music, you always crank up the latest radio pop tunes.",
"One to enjoy mixed drinks, you enjoy cups of goat urine and cow blood.",
"One to enjoy underwear, your closet is as impressive as it is worrisome.",
"One to enjoy poor interior design, you have green and blue curtains.",
"One to enjoy drinking lemonade, you spend days milking fresh lemons.",
"One to enjoy intellectual pursuits, you read your shampoo bottles daily.",
"One to enjoy socializing with celery, you're quite the stalker.",
"One to enjoy nature, you take long walks in the forest and eat dirt.",
"One to enjoy the dark arts, you tend to stub your toe a lot.",
"One to enjoy wildlife, you can tell the gender of most animals at a glance.",
"One to enjoy reading, you have a large collection of self-help books.",
"One to enjoy sports, you are very fond of balls.",
"One to enjoy eating, you always adhere to the ten-second rule.",
"One to enjoy spear throwing, you can impale a potato from a mile away.",
"One to enjoy a good potato, you enjoy them for both breakfast and dinner.",
"One to enjoy lazy afternoons, you spent most of your life on a couch.",
"One to enjoy squabbling, you fit right in on a pirate's shoulder.",
"One to enjoy walks in the forest, you are besieged by men in tights.",
"One to never delay the inevitable, you fill out your tax returns on time.",
"One to enjoy card games, you have a problem with gambling and itchy fingers.",
"One to enjoy cougars, you find yourself taking quests in an attempt to score.",
"One to never back down from a challenge, you hate the taste of chicken.",
"One with a sweet tooth, you trust in the mystical power of ketchup.",
"One who enjoys whale watching, you're quite the catch at viking bars.",
"One who is always punctual, you are ambushed surprisingly frequently.",
"One who can tie a cherry stem with his tongue, you are downright sexy.",
"One with a fondness for puppies, you enjoy kicking them.",
"One to always have a quirky one-liner, you're a hit with the ladies.",
"One who laughs in the face of danger, you have never stopped laughing.",
"One who is known to cry over spilt milk, you hate fighting cow warriors.",
"One to enjoy lemons, you have a tiny tiny mouth.",
"One to enjoy laissez-faire economics, you sell magic beans to peasants.",
"One to enjoy scatting, your friends never invite you over.",
"One who can't cry, you leak tears from your fists.",
"One who enjoys getting kicked repeatedly, you ask the woman to do so.",
"One to be quick with a joke or to light up a smoke, you're a hit at the bar.",
"One to be endowed with large breasts, you enjoy showing them off.",
"One to enjoy grass, you smell a bit dank and have stains on your clothes."};
	return enjoy[std::rand() % 50];
}

std::string TODAY(){
	std::string today[] = {"A few minutes ago, you walked outside and smelled the roses...",
"An hour ago, you wished for some clean underwear...",
"Half an hour ago, you tried to defecate on a sleeping man...",
"A few minutes ago, you forgot your own name...",
"Today, you thought that you were on drugs...",
"An hour ago, you went to the local pub and had a few beers...",
"A few minutes ago, you made a strange noise with your mouth...",
"An hour ago, you made a peach pie and ate it in one sitting...",
"Half an hour ago, you laid around, waiting to get mauled ...",
"Today, you went to the tavern and hit on some old women...",
"Today, you went to the arena and got hammered...",
"Half an hour ago, you were crushed by a boulder...",
"A few minutes ago, you woke up and drank a few health potions...",
"An hour ago, you baked a fresh peach cobbler and smiled...",
"Today, you made another sculpture of a giant moose...",
"This morning, you spilled some salt...",
"This morning, you broke a mirror while carrying it under a ladder...",
"Thirty seven seconds ago, you were complimented on your time abilities...",
"Today, you took a long walk and tripped on a pebble...",
"An hour ago, you forgot your father's name...",
"Half an hour ago, you put out a fire...",
"This morning, you contemplated the meaning of life, the universe, and all...",
"A few minutes ago, you tried to eat a pine cone...",
"An hour ago, you decided to work on your posture...",
"This morning, you resolved to be a pink hummingbird...",
"Today you felt like taking on the entire world...",
"Today felt like a good day to die...",
"Today you decided to take the first step of a thousand step journey...",
"An hour ago you defecated onto a potato...",
"12.34 minutes ago you resolved to be less obsessive compulsive...",
"Today you woke up hungry...",
"Today you thought, öwhat is up with today, today?ö...",
"Today you felt like eating a raw onion...",
"Only an hour ago you decided to give up the constraints of linear time...",
"Half an hour ago you felt like having an adventure...",
"Today, you promised yourself you wouldn't cry...",
"A couple hours ago, you found a lucky penny...",
"Just a minute ago, you got a wicked cramp in your leg...",
"A couple of hours ago, you avenged the death of your pet rock...",
"Today, you swore revenge on the mole people for eating your dog...",
"A couple hours ago, you watched a man kill himself with a fish...",
"Half an hour ago, you decided it would be a good idea to be a hero...",
"Twenty minutes ago, you didn't know how he met their mother...",
"An hour ago, you still had speedwalking champion on your bucket list...",
"Ten minutes ago, you decided to count to six hundred...",
"Today you found out that you were adopted...",
"Today you lost yourself in the woods...",
"Today you became a man...",
"A couple hours ago, you were a newt...",
"A few minutes ago, you hacked up a loogie..."};
	return today[std::rand() % 50];
}

std::string MISC(){
	std::string misc[] = {"a strange feeling overwhelms you as you convulse on the floor.",
"a strange odor fills your nostrils as you cry out in pain.",
"a melancholy clanging bell echoes in the distance as you fall asleep.",
"a strange smell enters your lungs as you pass out.",
"a powerful voice can be heard booming in the background.",
"a strange noise is heard in the background. It calls to you.",
"a strange soothing voice can be heard in the distance.",
"a booming voice is heard moaning in the background.",
"an eerie moan is heard a few inches away.",
"a loud siren blares in the background. You instantly pass out.",
"a strange odor makes its way into your eyes. You cry.",
"a strange smell lulls you to sleep. You slowly lose consciousness.",
"a strange siren starts vibrating, drawing you closer and closer to it.",
"a foul smell burns your skin. You scream in agony.",
"a foul smelling corpse hits you in the face like a ton of bricks.",
"a raven and a crow attack you. You curl into a ball until they leave.",
"a strange sensation rushes over you. You shiver.",
"a dark butt passes overhead. You close your eyes.",
"a brilliant light momentarily blinds you.",
"a skittering sound makes you jump.",
"a bean strikes you in the belly. You puke.",
"a wave of vertigo pushes you over.",
"an inexplicable feeling of dread makes love to the back of your neck.",
"a shriek is heard behind you. You go weak in the knees.",
"a blob of jello suddenly strikes you in the face. You have a panic attack.",
"a wave of darkness rolls across your vision. Everything fades to gray.",
"a burning feeling starts in your crotch, and engulfs your entire body.",
"a raw potato starts burning and smoking. It flies across the room.",
"your food disagrees with you. You pass out in a pool of your own vomit.",
"an unseen voice whispers in your ear. You turn and lose your balance.",
"a spider drops from the ceiling and waves hello. You scream.",
"a bunny comes out of a hole. You instantly punch yourself in the face.",
"you slip and hit your head. You are not sure how long you've been out.",
"you start choking on two chicken legs and pass out.",
"you put some chocolate syrup in your pants, and start choking yourself.",
"a mottled stranger in a cloak asks you what you're buying. You pass out.",
"a porpoise tap dances across the room then canes you over the head.",
"an elephant in a tutu asks you for directions to the circus and kisses you.",
"everything grows dark and the only thing you hear is your own breath.",
"you feel something crawling on your back, inch by inch.",
"you hear the telltale heartbeat of that potato you killed earlier.",
"rain pours out of nowhere and you turn your trench coat to it.",
"the sound of children laughing drills into your brain, driving you insane.",
"your tongue tastes like chicken. You almost decide to eat it.",
"you instantly grow a beard but it falls off and runs away.",
"a horse appears behind you and drops an invisible ocarina into your hands.",
"you find yourself naked in high school giving a presentation on breasts.",
"you hear the drip drop of falling water echoing in the distance.",
"you have a sudden craving for a big slice of cake, you monster.",
"you see a glimmer of light in the distance."};
	return misc[std::rand() % 50];
}

std::string SUDDENLY(){
	std::string suddenly[] = {"Suddenly, you find yourself in a strange room with an old woman.",
"Suddenly, you see a woman wearing a robe. She makes his way toward you.",
"Suddenly, you find yourself walking toward a strange woman.",
"Out of nowhere, you are startled by a burly woman who appears next to you.",
"Suddenly, you find yourself completely naked. A woman approaches.",
"Suddenly, you find yourself startled by a woman next to you.",
"Out of nowhere, you are groped by a woman standing next to you.",
"Suddenly, you are surprised by a shadowy figure next to you.",
"Suddenly, you find yourself frozen in terror. A woman approaches.",
"Suddenly, you find yourself drooling uncontrollably. A woman approaches.",
"Suddenly, a strange woman comes close to you and whispers in your ear.",
"Out of nowhere, a woman bursts into the room and kicks you in the face.",
"Out of nowhere, a muscular woman runs into the room and punches you.",
"Suddenly, a naked woman with a turtle shell comes in and sits next to you.",
"Suddenly, a woman appears in front of you and screams. You scream as well.",
"Out of nowhere, a woman in a banana suit hops towards you.",
"Suddenly, you notice a strange woman trying to give you a back rub.",
"Suddenly, a woman in a bathrobe holding a syringe appears near you.",
"Suddenly, a wild grue ap--wait, it's just a strange woman. She approaches you.",
"Out of nowhere, a woman appears next to you and shouts in your ear.",
"Out of nowhere, a runway-model-thin woman sashays over to you.",
"Out of nowhere, a woman wearing a fake mustache pokes you.",
"Suddenly, a wild STRANGER appeared! You are not amused.",
"Out of nowhere, a rather androgynous woman approaches you.",
"Out of nowhere, a woman dressed exactly like you runs up and punches you.",
"Suddenly, a bearded woman appears dressed in only a robe and stilettos.",
"Suddenly a robed woman runs up to you and hands you a piece of paper.",
"Out of nowhere, a woman dressed in a silk robe runs up and kicks you.",
"Suddenly, a woman saunters over and whispers seductively to you.",
"Out of nowhere, an androgynous figure runs up to you and cackles.",
"Suddenly, an old woman who looks like Deckard Cain comes into the room.",
"Suddenly, aour reflection steps out from a nearby mirror, and speaks to you.",
"Out of nowhere, a nearby pile of rocks forms into an old woman. He gazes at you.",
"Out of nowhere, a woman in a robe greets you with a raspy voice.",
"Suddenly, a masked figure appears in front of you and hands you a potato.",
"Suddenly, a woman in a tuxedo appears and asks how you like your martinis.",
"Suddenly, a woman approaches you, with her mouth open.",
"Suddenly, a woman appears among a flock of doves.",
"Suddenly, you feel the sweaty palm of someone behind you.",
"Suddenly, a masked potato appears behind you and hands you a woman.",
"Out of nowhere, a dude is waiting on you for a high five.",
"Out of nowhere, you see an old woman holding a lantern to his face.",
"Suddenly, a woman gives you a hug and tells you it's ok to cry.",
"Out of nowhere, a woman appears in front of you and begins to hum.",
"Out of nowhere, a seal claps its hands and transforms into a woman.",
"Suddenly, a skeleton decays in reverse, forming into the shape of a woman.",
"Suddenly, you decide to whistle a tune from childhood and summon a woman.",
"Out of nowhere, a woman pile-drives you into the floor.",
"Out of nowhere, your hair falls out and turns into a woman.",
"Suddenly, a woman flows into the room, wearing a black dress."};
	return suddenly[std::rand() % 50];
}

std::string UNSURE(){
	std::string unsure[] = {"Unsure of what to do next, you punch her in the face.",
"Unsure of her intentions, you slap her in the face.",
"Unsure of her intentions, you loudly scream 'RAPE' just in case.",
"Unsure of your surroundings, you start to cry tears of blood.",
"Unsure if friend or foe, you boldly do nothing.",
"Unsure of how she appeared there, you punch yourself in the face.",
"Unsure if it is a man or a woman, you try to fondle him or her.",
"Unsure if she is trying to kill you, you freeze in terror.",
"Unsure if she is trying hurt you, you punch yourself in the face.",
"Unsure if you are dreaming, you punch yourself in the face.",
"Unsure whether she is a hermaphrodite, you kick her in the shin.",
"Unsure whether she is trying to abduct you, you kick her in the face.",
"Unsure whether she is wearing a wig, you try to pull it off.",
"Unsure if the woman is a thief, you try to run away.",
"Unsure if the woman is a beggar, you toss your shoes at her.",
"Unsure of her intentions, you put your fists up.",
"Unsure of her intentions, you fall over backwards.",
"Unsure if the woman is an assassin, you begin to call for help.",
"Unsure if you have been drugged, you poke yourself in the eye.",
"Unsure of her intentions, you bite your fingernails.",
"Unsure if you are dreaming, you try to will her into a beautiful wowoman.",
"Unsure if she is attempting murder, you try to stab her with a potato.",
"Unsure if you are dreaming, you try to fly by flapping your arms.",
"Unsure of her intentions, you start quacking like a duck.",
"Unsure if she is going to hold you for ransom, you punch yourself.",
"Unsure if you're seeing an an illusion, you punch yourself in the groin.",
"Unsure if the woman is armed or not, you start feeling for her arms.",
"Unsure if you enjoy her smell or not, you grab her hair and take a whiff.",
"Unsure of the figure before you, you crawl over and sniff her crotch.",
"Unsure of the womanÆs intentions, you ask her what she wants of you.",
"Unsure if the woman is hungry, you offer her a piece of your cake.",
"Unsure of the proper protocol, you punch yourself in the thighs.",
"Unsure if the woman is dangerous, you kick her in the groin.",
"Unsure if that is a good thing, you close your eyes and scream.",
"Unsure if your life is in danger, you attempt to run away.",
"Unsure if you understand what's going on, you call 1-800-CONTEXT.",
"Unsure of what you're seeing, you rub sawdust in your eyes.",
"Unsure of your loyalty to tubers, you throw a potato at her.",
"Unsure of your bladder, you try to mark your territory to hide the shame.",
"Unsure if you're in danger, you play dead.",
"Unsure if ther woman is your long lost uncle, you touch her face.",
"Unsure if the woman is an illusion, you attempt to lick her.",
"Unsure of your own mortality, you punch yourself with the woman's fist.",
"Utterly confused, you drool onto the floor.",
"Dumbstruck, you try to say something but end up pooping instead.",
"Slightly confused, you scratch your crotch then shake the woman's hand.",
"Utterly confused, you pull a chunk of your hair out and toss it around.",
"Unsure of your sexuality, you kiss the woman then punch her in the face.",
"Utterly confused, you absentmindedly drink that bottle of yellow liquid.",
"With complete confidence in your demeanor, you smack her in the face"};
	return unsure[std::rand() % 50];
}
