#ifndef _SKILLID_H
#define _SKILLID_H

enum class SKILL{
	REPOSITION,
	BARBARIAN_CLEAVE,
	BARBARIAN_EXBASH,
	BARBARIAN_WHIRLWIND,
	BARBARIAN_EXWHIRLWIND,
	BARBARIAN_FRENZY,
	BARBARIAN_SIESMICSLAM,
	FINALBLOW,
};

#endif